title: "The Nerd Tavern"
description: "Porque todo RPG começa em uma Taverna"
url: "https://thenerdtavern.github.io"
baseurl: "/project-v4"
author: "Tarbeneiro"
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs
